BEGIN;

ALTER TABLE run_webhook_subscriptions RENAME TO task_callback_subscriptions;
ALTER TABLE run_webhook_deliveries RENAME TO task_callback_deliveries;

ALTER TABLE task_callback_subscriptions RENAME COLUMN push_auth_scheme TO auth_scheme;
ALTER TABLE task_callback_subscriptions RENAME COLUMN push_auth_credentials TO auth_credentials;
ALTER TABLE task_callback_subscriptions RENAME COLUMN push_metadata TO metadata;

ALTER INDEX IF EXISTS idx_run_webhook_subscriptions_run RENAME TO idx_task_callback_subscriptions_run;
ALTER INDEX IF EXISTS idx_run_webhook_subscriptions_active RENAME TO idx_task_callback_subscriptions_active;
ALTER INDEX IF EXISTS idx_run_webhook_deliveries_subscription_event RENAME TO idx_task_callback_deliveries_subscription_event;
ALTER INDEX IF EXISTS idx_run_webhook_deliveries_pending RENAME TO idx_task_callback_deliveries_pending;
ALTER INDEX IF EXISTS idx_run_webhook_deliveries_subscription RENAME TO idx_task_callback_deliveries_subscription;

ALTER TRIGGER run_webhook_subscriptions_set_updated_at ON task_callback_subscriptions RENAME TO task_callback_subscriptions_set_updated_at;
ALTER TRIGGER run_webhook_deliveries_set_updated_at ON task_callback_deliveries RENAME TO task_callback_deliveries_set_updated_at;

ALTER TABLE task_callback_subscriptions RENAME CONSTRAINT run_webhook_subscriptions_pkey TO task_callback_subscriptions_pkey;
ALTER TABLE task_callback_subscriptions RENAME CONSTRAINT run_webhook_subscriptions_status_valid TO task_callback_subscriptions_status_valid;
ALTER TABLE task_callback_subscriptions RENAME CONSTRAINT run_webhook_subscriptions_failures_nonneg TO task_callback_subscriptions_failures_nonneg;
ALTER TABLE task_callback_subscriptions RENAME CONSTRAINT run_webhook_subscriptions_event_types_nonempty TO task_callback_subscriptions_event_types_nonempty;
ALTER TABLE task_callback_subscriptions RENAME CONSTRAINT run_webhook_subscriptions_url_len TO task_callback_subscriptions_url_len;
ALTER TABLE task_callback_subscriptions RENAME CONSTRAINT run_webhook_subscriptions_push_auth_scheme_len TO task_callback_subscriptions_auth_scheme_len;
ALTER TABLE task_callback_subscriptions RENAME CONSTRAINT run_webhook_subscriptions_push_auth_credentials_len TO task_callback_subscriptions_auth_credentials_len;
ALTER TABLE task_callback_subscriptions RENAME CONSTRAINT run_webhook_subscriptions_push_metadata_object TO task_callback_subscriptions_metadata_object;

ALTER TABLE task_callback_deliveries RENAME CONSTRAINT run_webhook_deliveries_pkey TO task_callback_deliveries_pkey;
ALTER TABLE task_callback_deliveries RENAME CONSTRAINT run_webhook_deliveries_subscription_id_fkey TO task_callback_deliveries_subscription_id_fkey;
ALTER TABLE task_callback_deliveries RENAME CONSTRAINT run_webhook_deliveries_run_event_id_fkey TO task_callback_deliveries_run_event_id_fkey;
ALTER TABLE task_callback_deliveries RENAME CONSTRAINT run_webhook_deliveries_status_valid TO task_callback_deliveries_status_valid;

COMMIT;
