BEGIN;

ALTER TABLE task_callback_deliveries RENAME CONSTRAINT task_callback_deliveries_status_valid TO run_webhook_deliveries_status_valid;
ALTER TABLE task_callback_deliveries RENAME CONSTRAINT task_callback_deliveries_run_event_id_fkey TO run_webhook_deliveries_run_event_id_fkey;
ALTER TABLE task_callback_deliveries RENAME CONSTRAINT task_callback_deliveries_subscription_id_fkey TO run_webhook_deliveries_subscription_id_fkey;
ALTER TABLE task_callback_deliveries RENAME CONSTRAINT task_callback_deliveries_pkey TO run_webhook_deliveries_pkey;

ALTER TABLE task_callback_subscriptions RENAME CONSTRAINT task_callback_subscriptions_metadata_object TO run_webhook_subscriptions_push_metadata_object;
ALTER TABLE task_callback_subscriptions RENAME CONSTRAINT task_callback_subscriptions_auth_credentials_len TO run_webhook_subscriptions_push_auth_credentials_len;
ALTER TABLE task_callback_subscriptions RENAME CONSTRAINT task_callback_subscriptions_auth_scheme_len TO run_webhook_subscriptions_push_auth_scheme_len;
ALTER TABLE task_callback_subscriptions RENAME CONSTRAINT task_callback_subscriptions_url_len TO run_webhook_subscriptions_url_len;
ALTER TABLE task_callback_subscriptions RENAME CONSTRAINT task_callback_subscriptions_event_types_nonempty TO run_webhook_subscriptions_event_types_nonempty;
ALTER TABLE task_callback_subscriptions RENAME CONSTRAINT task_callback_subscriptions_failures_nonneg TO run_webhook_subscriptions_failures_nonneg;
ALTER TABLE task_callback_subscriptions RENAME CONSTRAINT task_callback_subscriptions_status_valid TO run_webhook_subscriptions_status_valid;
ALTER TABLE task_callback_subscriptions RENAME CONSTRAINT task_callback_subscriptions_pkey TO run_webhook_subscriptions_pkey;

ALTER TRIGGER task_callback_deliveries_set_updated_at ON task_callback_deliveries RENAME TO run_webhook_deliveries_set_updated_at;
ALTER TRIGGER task_callback_subscriptions_set_updated_at ON task_callback_subscriptions RENAME TO run_webhook_subscriptions_set_updated_at;

ALTER INDEX IF EXISTS idx_task_callback_deliveries_subscription RENAME TO idx_run_webhook_deliveries_subscription;
ALTER INDEX IF EXISTS idx_task_callback_deliveries_pending RENAME TO idx_run_webhook_deliveries_pending;
ALTER INDEX IF EXISTS idx_task_callback_deliveries_subscription_event RENAME TO idx_run_webhook_deliveries_subscription_event;
ALTER INDEX IF EXISTS idx_task_callback_subscriptions_active RENAME TO idx_run_webhook_subscriptions_active;
ALTER INDEX IF EXISTS idx_task_callback_subscriptions_run RENAME TO idx_run_webhook_subscriptions_run;

ALTER TABLE task_callback_subscriptions RENAME COLUMN metadata TO push_metadata;
ALTER TABLE task_callback_subscriptions RENAME COLUMN auth_credentials TO push_auth_credentials;
ALTER TABLE task_callback_subscriptions RENAME COLUMN auth_scheme TO push_auth_scheme;

ALTER TABLE task_callback_deliveries RENAME TO run_webhook_deliveries;
ALTER TABLE task_callback_subscriptions RENAME TO run_webhook_subscriptions;

COMMIT;
