BEGIN;

DROP TRIGGER IF EXISTS workflow_run_cancellations_external_execution_wake_update ON workflow_run_cancellations;
DROP TRIGGER IF EXISTS workflow_run_cancellations_external_execution_wake_insert ON workflow_run_cancellations;
DROP TRIGGER IF EXISTS run_cancellations_external_execution_wake_update ON run_cancellations;
DROP TRIGGER IF EXISTS run_cancellations_external_execution_wake_insert ON run_cancellations;
DROP TRIGGER IF EXISTS external_executions_cancellation_wake_update ON external_executions;
DROP TRIGGER IF EXISTS external_execution_cancellations_wake_update ON external_execution_cancellations;
DROP TRIGGER IF EXISTS external_execution_cancellations_wake_insert ON external_execution_cancellations;
DROP FUNCTION IF EXISTS emit_external_execution_wake_notification();

COMMIT;
